### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by pastukhov** [sreuter/node-speakable#11]
On ubuntu with nodejs v0.10.25
```bash
artem@artem-desktop-bt:~/build/node-speakable$ 
node example.js 
onSpeechReady

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

**Comment by ejferg** [comment]
Same here.

**Comment by ejferg** [comment]
ooops...forgot to include the sox binary in the lib folder.

**Comment by ewnd9** [comment]
quick instruction for ubuntu

```
$ sudo apt-get install sox
$ ln -s /usr/bin/sox lib/
```
