### ISSUE TITLE
I have an issue when I execute example.js

### ISSUE THREAD

**Issue by pirmax** [sreuter/node-speakable#19]
> C:\Users\Maxence\Desktop\node-speakable-master\node-speakable-master  (speakable@0.4.0)
> λ node example.js
> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn C:\Users\Maxence\Desktop\node-speakable-master\node-speakable-master\lib/sox ENOENT
>     at exports._errnoException (util.js:1022:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
>     at onErrorNT (internal/child_process.js:359:16)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
>     at Module.runMain (module.js:607:11)
>     at run (bootstrap_node.js:420:7)
>     at startup (bootstrap_node.js:139:9)
>     at bootstrap_node.js:535:3

**Comment by sokyrko** [comment]
`Currently node-speakable needs you to put a binary of sox into the modules (into lib) folder to do the recording. `
